global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: dop-services
    metrics_path: /metrics
    static_configs:
      - targets:
          - order-service:8081
          - inventory-service:8082
          - payment-service:8083
        labels:
          stack: dop
